# Site settings
title: Mist Of Eden
email: mistofeden.blog@gmail.com
description: The official website of Mist Of Eden
about: > # this means to ignore newlines until "baseurl:"
  Dedicated to providing the vaping community orginal and curated content
  covering the many different aspects of vaping, including but not limited to:
  safety and health, interviews and guest articles, product reviews, and of
  course advocacy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mistofeden.github.io/" # the base hostname & protocol for your site
youtubechannel_name: mistofeden
twitter_username: mistofeden
github_username:  mistofeden

# page meta data
keywords: vaping, e-cigs, e-juice
creator: Jeffrey Schwartz
publisher: Jeffrey Schwartz
editorinchief: Jeffrey T. Schwartz, Editor-in-Chief
googlebot: index, follow
robots: index, follow
slurp: index, follow

# Build settings
markdown: kramdown
