# Site settings
title: Mist Of Eden
email: mistofeden.blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mistofeden.github.io" # the base hostname & protocol for your site
youtubechannel_name: mistofeden
twitter_username: mistofeden
github_username:  mistofeden

# Build settings
markdown: kramdown
