# Site settings
title: Mist Of Eden
email: mistofeden.blog@gmail.com
description: The official Mist Of Eden webzine
about: > # this means to ignore newlines until "baseurl:"
  Dedicated to providing the vaping community original and curated content
  covering the many different and diverse aspects of vaping, including but not
  limited to: safety and health, interviews and guest articles, product reviews,
  and of course advocacy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mistofeden.github.io/" # the base hostname & protocol for your site
siteImg: "/images/vape-vaping-smoking-woman.jpg"

# social media
youtube_channelname: mistofeden
youtube_channelurl: https://www.youtube.com/channel/UCOEVj-vXLLwSGZTyEvdGGbA
facebook_pagename: Mist Of Eden
facebook_pageurl: https://www.facebook.com/pages/Mist-Of-Eden/506525579510933
twitter_username: mistofeden
github_username:  mistofeden

# page meta tag data
keywords: vaping, e-cigs, e-juice
creator: Jeffrey Schwartz
publisher: Jeffrey Schwartz
editorinchief: Jeffrey T. Schwartz, Editor-in-Chief

#web crawler data
googlebot: index, follow
robots: index, follow
slurp: index, follow

# Build settings
markdown: kramdown
