# Site settings
title: Mist Of Eden
email: mistofeden.blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the Mist Of Eden where you can find content covering the many
  different aspects of vaping, including but not limited to: safety and health,
  interviews and guest articles, hardware and e-juice reviews, and of course
  advocacy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mistofeden.github.io/" # the base hostname & protocol for your site
youtubechannel_name: mistofeden
twitter_username: mistofeden
github_username:  mistofeden

# page meta data
keywords: vaping, e-cigs, e-juice
creator: Jeffrey Schwartz
publisher: Jeffrey Schwartz
googlebot: index, follow
robots: index, follow
slurp: index, follow

# Build settings
markdown: kramdown
